version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: vkflwldhr1234
      MYSQL_DATABASE: venus_planner
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis
    restart: always
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/redis

volumes:
  mysql:
  redis: